# Generated by Django 5.2.15 on 2026-06-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'beneficio',
                'verbose_name_plural': 'beneficios',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('servicio_interes', models.CharField(blank=True, help_text='Slug de Servicio o Proyecto.slug_demo elegido en el formulario.', max_length=60, verbose_name='servicio de interés')),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notificado_por_email', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('resumen', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='boletin/')),
                ('publicada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'noticia',
                'verbose_name_plural': 'noticias (boletín)',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Dyxersoft', max_length=100)),
                ('tagline', models.CharField(default='Soluciones SaaS, IA y Gestión Inteligente de Incidencias', max_length=200)),
                ('mision', models.TextField(default='Somos un equipo multidisciplinario de desarrolladores, ingenieros de datos, diseñadores y consultores tecnológicos con base en Santa Cruz de la Sierra, Bolivia. Nuestra visión es clara: ayudar a empresas latinoamericanas a escalar con tecnología de clase mundial. Combinamos experiencia local con estándares globales para entregar soluciones que realmente funcionan. Desde plataformas SaaS hasta proyectos de inteligencia artificial, trabajamos con metodologías ágiles, soporte continuo y un compromiso real con el éxito de nuestros clientes.', verbose_name='misión y visión')),
                ('ciudad', models.CharField(default='Santa Cruz de la Sierra, Bolivia', max_length=100)),
                ('anios_experiencia', models.PositiveIntegerField(default=5, verbose_name='años de experiencia')),
                ('clientes_activos', models.PositiveIntegerField(default=30, verbose_name='clientes activos')),
                ('porcentaje_compromiso', models.PositiveIntegerField(default=100, verbose_name='% compromiso con calidad')),
                ('email_contacto', models.EmailField(default='contacto@dyxersoft.com', max_length=254)),
                ('whatsapp', models.CharField(default='+591 620694477', max_length=30)),
                ('linkedin_url', models.URLField(default='https://linkedin.com/company/dyxersoft')),
                ('facebook_url', models.URLField(default='https://facebook.com/dyxersoft')),
            ],
            options={
                'verbose_name': 'perfil de la empresa',
                'verbose_name_plural': 'perfil de la empresa',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('icono', models.CharField(blank=True, help_text='Ej: bi-cloud, bi-cpu', max_length=50, verbose_name='clase de icono (Bootstrap Icons)')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('descripcion_larga', models.TextField(blank=True)),
                ('cliente', models.CharField(blank=True, help_text='Ej: DUBSS - UAGRM', max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='portafolio/')),
                ('slug_demo', models.SlugField(help_text='Valor usado en ?servicio=<slug_demo> al precargar el formulario de contacto.', max_length=160, verbose_name="slug para 'Solicitar demo'")),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('servicio_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='sitio.servicio')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos (portafolio)',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
